apiVersion : apps/v1
kind: Deployment
metadata:
  name: "rktwohat-0f97"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "rktwohat-0f97"
  template:
    metadata:
      labels:
        app: "rktwohat-0f97"
    spec:
      containers:
        - name: "rktwohat-0f97"
          image: "twohat.azurecr.io/rktwohat"
          ports:
          - containerPort: 80